---
- name: Deploy YC app infrastructure
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Deploy YC app with terraform
      terraform:
        force_init: true
        project_path: ../../terraform
        state: "{{ tf_state }}"
        backend_config:
          endpoint  : "storage.yandexcloud.net"
          bucket    : "{{ tf_bucket_name }}"
          region    : "us-east-1"
          key       : "{{ tf_bucket_state_file_name }}"
          access_key: "{{ tf_bucket_access_key }}"
          secret_key: "{{ tf_bucket_secret_key }}"
          skip_region_validation     : "true"
          skip_credentials_validation: "true"
    - meta: refresh_inventory

- name: Deploy docker on app infrastructure
  hosts: app_hosts
  become: true
  gather_facts: false

  pre_tasks:
    - name: Wait connection
      wait_for_connection:
    - name: Gather facts
      setup:
    - name: Install Python3-pip
      apt:
        name: python3-pip
        update_cache: true
    - name: Install python modules docker and docker-compose
      pip:
        name: 
          - docker
          - docker-compose

  roles:
    - role: geerlingguy.docker
      vars:
        docker_users: ubuntu

  tasks:
    - name: Deploy app images
      include_tasks: app.yml

- name: Configure monitoring
  hosts: monitoring_hosts
  become: true
  tasks:

    - name: Run monitoring configure tasks
      include_tasks: monitoring.yml
