---
- name: Create directories
  file:
    path: "/srv/gitlabrunner-{{ '%02d' | format(item) }}"
    state: directory
  loop: "{{ range(0, runners_count)|list }}"

- name: Wait for gitlab configure
  wait_for:
    path: /srv/gitlab/logs/reconfigure
    delay: 20
- name: Read gitlab configurire log
  find:
    paths: /srv/gitlab/logs/reconfigure
    file_type: file
    patterns: '*.log'
  register: res
- name: Wait for gitlab configure
  wait_for:
    path: "{{ res.files[0].path }}"
    timeout: 600
    search_regex: 'INFO: Report handlers complete'

- name: Gitlab runner registration
  include_tasks: register_runner.yml
  loop: "{{ range(0, runners_count)|list }}"

- name: Deploy Gitlab runner
  docker_container:
    container_default_behavior: compatibility
    name: "gitlab-runner-{{ '%02d' | format(item) }}"
    image: gitlab/gitlab-runner:latest
    state: started
    restart_policy: always
    volumes:
      - "/srv/gitlabrunner-{{ '%02d' | format(item) }}/config:/etc/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - name: gitlab-net
        aliases:
          - "gitlab-runner-{{ '%02d' | format(item) }}"
    purge_networks: true
  loop: "{{ range(0, runners_count)|list }}"

- debug:
    msg: |
      "Gitlab address: http://{{ ansible_host }}.xip.io"
      "Gitlab token: {{ gitlab_runner_token }}"
