- name: Create directories
  file:
    path: "/srv/gitlabrunner-{{ '%02d' | format(item) }}"
    state: directory
  loop: "{{ range(0, runners_count)|list }}"

- name: Deploy Gitlab runner image
  docker_container:
    container_default_behavior: compatibility
    name: "gitlab-runner-{{ '%02d' | format(item) }}"
    image: gitlab/gitlab-runner:latest
    state: started
    restart_policy: always
    volumes:
      - "/srv/gitlabrunner/config-{{ '%02d' | format(item) }}:/etc/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - name: gitlab-net
        aliases:
          - "gitlab-runner-{{ '%02d' | format(item) }}"
    purge_networks: true
  loop: "{{ range(0, runners_count)|list }}"

- name: Wait for gitlab configure
  wait_for:
    path: /srv/gitlab/logs/reconfigure
    delay: 20
- name: Read gitlab configurire log
  find:
    paths: /srv/gitlab/logs/reconfigure
    file_type: file
    patterns: '*.log'
  register: res
- name: Wait for gitlab configure
  wait_for:
    path: "{{ res.files[0].path }}"
    timeout: 600
    search_regex: 'INFO: Report handlers complete'

- name: Register runner
  command: >
    docker exec -it gitlab-runner-{{ '%02d' | format(item) }} gitlab-runner register \
        --url http://gitlab-ci/ \
        --non-interactive \
        --locked=false \
        --name DockerRunner-{{ '%02d' | format(item) }} \
        --executor docker \
        --docker-image alpine:latest \
        --registration-token {{ gitlab_runner_token }} \
        --tag-list "linux,xenial,ubuntu,docker" \
        --run-untagged
  changed_when: false
  loop: "{{ range(0, runners_count)|list }}"

- debug:
    msg: |
      "Gitlab IP: {{ ansible_host }}"
      "token: {{ gitlab_runner_token }}"
