---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /srv/gitlab/config
    - /srv/gitlab/data
    - /srv/gitlab/logs

- name: Create gitlab network
  docker_network:
    name: gitlab-net
