---
- name: Check that the runner has not been registered yet
  stat:
    path: "/srv/gitlabrunner-{{ '%02d' | format(item) }}/config/config.toml"
  register: runner_reg

- name: Register Gitlab runner
  docker_container:
    container_default_behavior: compatibility
    name: "gitlab-runner-register-{{ '%02d' | format(item) }}"
    image: gitlab/gitlab-runner:latest
    state: started
    auto_remove: true
    volumes:
      - "/srv/gitlabrunner-{{ '%02d' | format(item) }}/config:/etc/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - name: gitlab-net
        aliases:
          - "gitlab-runner-register-{{ '%02d' | format(item) }}"
    purge_networks: true
    command: >
        register 
        --url http://gitlab-ci/ 
        --non-interactive 
        --locked=false 
        --name DockerRunner-{{ '%02d' | format(item) }} 
        --executor docker 
        --docker-image alpine:latest 
        --registration-token {{ gitlab_runner_token }} 
        --tag-list "docker" 
        --run-untagged
  when: not runner_reg.stat.exists
