{
 "title": "App Crawler",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "UI - Number of pages served by frontend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "web_pages_served", "legendFormat": "Pages" }
   ]
  },
  {
   "title": "Crawler - How much time it took to parse a page",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(crawler_page_parse_time_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "UI - Page generation time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(web_page_gen_time_bucket[5m])) by (le))",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "Crawler - How much time it took for crawler to get page",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(crawler_site_connection_time_bucket[5m])) by (le))",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "Crawler - Number of pages parsed by crawler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Pages" }
   ],
   "targets": [
    { "expr": "crawler_pages_parsed", "legendFormat": "{{job}} pages parsed" }
   ]
  }
 ]
}