version: '3.3'
services:

  node-exporter:
    image: prom/node-exporter:v1.0.1
    user: root
    ports: 
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      back_net:
        aliases:
          - node_exporter

  mongodb:
    image: mongo:3.2
    volumes:
      - mongodb:/data/db
    networks:
      back_net:
        aliases: 
          - mongodb

  rabbitmq:
    image: rabbitmq:alpine
    volumes:
      - rabbit-vol:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=${MQ_PASS:-12345678}
    networks:
      back_net:
        aliases:
          - rabbitmq

  ui:
    build:
      context: ./search_engine_ui
    ports:
      - 80:8000
    environment:
      - MONGO=mongodb
      - MONGO_PORT=27017
    networks:
      back_net:
        aliases:
          - app-ui
      front_net:
    depends_on:
      - mongodb

  crawler:
    build:
      context: ./search_engine_crawler
    ports:
      - 8001:8000
    environment:
      - MONGO=mongodb
      - MONGO_PORT=27017
      - RMQ_HOST=rabbitmq
      - RMQ_QUEUE=queue
      - RMQ_USERNAME=user
      - RMQ_PASSWORD=${MQ_PASS:-12345678}
      - EXCLUDE_URLS='.*github.com'
    networks:
      back_net:
        aliases:
          - app-crawler
      front_net:
    depends_on:
      - rabbitmq
      - mongodb

volumes:
  mongodb:
  rabbit-vol:

networks:
  back_net:
  front_net:
