---
- name: Create dirs for data volumes, configs and compose files
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - /srv/prometheus/config
    - /srv/promethus/compose

- name: Create docker-compose for prometheus
  template:
    src: ../templates/docker-compose-monitoring.yml.j2
    dest: /srv/promethus/compose/docker-compose.yml

- name: Create prometheus config file
  template:
    src: ../templates/prometheus.yml.j2
    dest: /srv/prometheus/config/prometheus.yml

- name: run docker-compose up
  docker_compose:
    project_src: /srv/promethus/compose/
